<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-24T12:51:00 IST" name="Suite" finished-at="2022-08-24T12:51:53 IST" duration-ms="53016">
    <groups>
      <group name="Smoke">
        <method signature="eCommerenceTest1.FillForm_ErrorMessage()[pri:0, instance:Appium.appiumframewokdesign.eCommerenceTest1@3a4621bd]" name="FillForm_ErrorMessage" class="Appium.appiumframewokdesign.eCommerenceTest1"/>
        <method signature="eCommerenceTest1.FillForm_PositiveFlow()[pri:0, instance:Appium.appiumframewokdesign.eCommerenceTest1@3a4621bd]" name="FillForm_PositiveFlow" class="Appium.appiumframewokdesign.eCommerenceTest1"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2022-08-24T12:51:00 IST" name="Error Test1" finished-at="2022-08-24T12:51:00 IST" duration-ms="19">
    </test> <!-- Error Test1 -->
    <test started-at="2022-08-24T12:51:00 IST" name="Error Test" finished-at="2022-08-24T12:51:53 IST" duration-ms="52471">
      <class name="Appium.appiumframewokdesign.eCommerenceTest1">
        <test-method is-config="true" signature="start()[pri:0, instance:Appium.appiumframewokdesign.eCommerenceTest1@3a4621bd]" started-at="2022-08-24T12:51:00 IST" name="start" finished-at="2022-08-24T12:51:18 IST" duration-ms="17390" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method is-config="true" signature="homePage()[pri:0, instance:Appium.appiumframewokdesign.eCommerenceTest1@3a4621bd]" started-at="2022-08-24T12:51:18 IST" name="homePage" finished-at="2022-08-24T12:51:22 IST" duration-ms="3726" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homePage -->
        <test-method signature="FillForm_ErrorMessage()[pri:0, instance:Appium.appiumframewokdesign.eCommerenceTest1@3a4621bd]" started-at="2022-08-24T12:51:22 IST" name="FillForm_ErrorMessage" finished-at="2022-08-24T12:51:30 IST" duration-ms="8313" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please your name] but found [Please enter your name]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please your name] but found [Please enter your name]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Appium.appiumframewokdesign.eCommerenceTest1.FillForm_ErrorMessage(eCommerenceTest1.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FillForm_ErrorMessage -->
        <test-method is-config="true" signature="homePage()[pri:0, instance:Appium.appiumframewokdesign.eCommerenceTest1@3a4621bd]" started-at="2022-08-24T12:51:31 IST" name="homePage" finished-at="2022-08-24T12:51:35 IST" duration-ms="4032" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homePage -->
        <test-method signature="FillForm_PositiveFlow()[pri:0, instance:Appium.appiumframewokdesign.eCommerenceTest1@3a4621bd]" started-at="2022-08-24T12:51:35 IST" name="FillForm_PositiveFlow" finished-at="2022-08-24T12:51:53 IST" duration-ms="17659" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FillForm_PositiveFlow -->
      </class> <!-- Appium.appiumframewokdesign.eCommerenceTest1 -->
    </test> <!-- Error Test -->
  </suite> <!-- Suite -->
</testng-results>
